### ISSUE TITLE
Scrolling broken in iOS

### ISSUE THREAD

**Issue by MagicFab** [getgnulinux/getgnulinux#13]
Someone has reported scrolling to be broken on iOS:
http://www.reddit.com/r/opensource/comments/24cvir/get_gnulinux_a_simple_concise_website_to_provide/ch60493

Although not the primary audience, it's also important for the site to be fully functional on iOS devices.

**Comment by figure002** [comment]
Better late than never?

Fixed in c0ae2739f4de3fe06df31dce874dcb91fc44bc55
