### ISSUE TITLE
Small issue in russian translation

### ISSUE THREAD

**Issue by Kaned1as** [getgnulinux/getgnulinux#16]
> Доугие разработчики GNU/Linux

should be 

> Другие разработчики GNU/Linux

on page http://www.getgnulinux.org/linux/linux_faq/#gnu

**Comment by goodwin64** [comment]
1)
> Не смотря на это, сообщество
should be
> Несмотря на это, сообщество
on [this page](http://www.getgnulinux.org/ru/switch_to_linux/from_windows_to_linux/)

2) Header
> Выбрирать при старте
should be
> Выбирать при старте
[here](http://www.getgnulinux.org/ru/switch_to_linux/try_or_install/)

3)
> (намного лучшим чем просто беслатное)
should be
> (намного лучшим чем просто бесплатное)
[here](http://www.getgnulinux.org/ru/windows/restrictions/)

**Comment by figure002** [comment]
@goodwin64 Apologies, only noticed your comment just now. If you can, please make any translation fixes on Transifex (see https://blog.getgnulinux.org/participate/translation/).
