### ISSUE TITLE
Wrong sentence（chinese）

### ISSUE THREAD

**Issue by IFRFSX** [getgnulinux/getgnulinux#38]
为什么有的 GNU/Linux 发行版并不完全免费？
有些 GNU/Linux 发行版尽管免费，但是却包含限制性的软件。这是为什么呢？

It should be changed to：

为什么有的 GNU/Linux 发行版并不完全自由？
有些 GNU/Linux 发行版尽管自由，但是却包含限制性的软件。这是为什么呢？

**Comment by figure002** [comment]
Thank you for the report! I fixed the sentence as you described.
Also, note that you yourself can update the translations as well, see https://blog.getgnulinux.org/participate/translation/
