### ISSUE TITLE
Support italics in translations

### ISSUE THREAD

**Issue by jorgesumle** [getgnulinux/getgnulinux#70]
Sometimes I needed to write in italics. I couldn't because of [Weblate's unsafe HTML check](https://docs.weblate.org/es/latest/user/checks.html#check-safe-html), which is very conservatively configured, because it doesn't allow HTML like `<i lang="en">software</i>`. I could use quotes for foreign words, but at some point there are quotes around foreign words («software libre»), and it would be very weird to write «"software" libre».

**Comment by figure002** [comment]
I removed the `safe-html` flag from the settings, so you should be able to do italics now. I trust that translators don't insert unsafe HTML. Please let me know if this fixes it.

And also thank you for completing the Spanish translation! We get many visitors from Spain, so this is a big win.

**Comment by jorgesumle** [comment]
I changed «software» and «hardware» to `<i lang="en">software</i>` and `<i lang="en">hardware</i>` using sed and uploaded the updated PO file to Weblate. I reviewed it, and it didn't do anything unexpected, so it should be OK now.
