### ISSUE TITLE
Search engine optimization

### ISSUE THREAD

**Issue by figure002** [getgnulinux/getgnulinux#71]
Currently, the website does not appear at all in search engine results for "linux" or "get linux" or "what is linux". This is probably the result of the usage of the term "GNU/Linux" everywhere on the website. Hence, when searching for "what is gnu linux" our website _is_ often listed on top. But people don't usually include "GNU" when searching for "Linux" because they probably never heard of GNU. So we need to do some SEO so that our website shows up in searches for "what is linux" as well.

**Comment by UnregisteredGuest** [comment]
Hey, I just stumbled upon your website, great work! Yeah, it doesn't seem to show up when I search for "what is linux," but does when I search for "what is gnu linux." 
My suggestion would be to just switch to calling it Linux; yes, that's _technically_ incorrect, but: people already call it that all the time, it would be less confusing for beginners, and -- as you said -- it would be better for SEO. 

If you did that, there could be a new page explaining the correlation between GNU and Linux.

Although this does leave the issue of your domain...

**Comment by figure002** [comment]
Moved to GitLab.
