### ISSUE TITLE
Use em dash instead of hyphen

### ISSUE THREAD

**Issue by jorgesumle** [getgnulinux/getgnulinux#77]
I think it's wrong to use a hyphen here ("of the restrictive license - such restrictions"):

![Captura de pantalla de 2023-04-12 01-32-03](https://user-images.githubusercontent.com/14212780/231310957-a926d284-afef-44ff-a5b4-8d686838a357.png)

Maybe there are other sentences where this punctuation mark is used.

See https://en.wikipedia.org/wiki/Dash#Em_dash and https://english.stackexchange.com/questions/2116/when-should-i-use-an-em-dash-an-en-dash-and-a-hyphen for information about this punctuation mark.

**Comment by figure002** [comment]
Moved to GitLab.
